# Generated by Django 5.1.6 on 2025-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://tse2.mm.bing.net/th?id=OIP.GJMl2OLHcXLBHoj672_JggHaHa&pid=Api&P=0&h=180')),
                ('cuisine', models.CharField(max_length=203)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
